name: PHP CI/CD Workflow

on:
  push:
    branches:
      - dev
      - prod

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # Add steps here to set up PHP, install dependencies, and run tests if applicable

  deploy_to_dev:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "cresoluser"
          git config user.email "cresoluser@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.CICD }}@github.com/cresoluser/cresol.git

      - name: Push to development branch
        run: |
          git checkout -b dev
          git push -f origin dev

      - name: FTP Deploy Action To Dev
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          if: "github.event_name == 'push' && github.ref == 'refs/heads/dev'"
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # If your whole repo should be uploaded
          server-dir: /dev/  # Your FTP path

  deploy_to_prod:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config user.name "cresoluser"
          git config user.email "cresoluser@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.CICD }}@github.com/cresoluser/cresol.git

      - name: Push to production branch
        run: |
          git checkout -b prod
          git push -f origin prod

      - name: FTP Deploy Action To Prod
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          if: "github.event_name == 'push' && github.ref == 'refs/heads/prod'"
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  # If your whole repo should be uploaded
          server-dir: /prod/  # Your FTP path
