name: PHP CI/CD Workflow

on: 
  push:
    branches:
      - dev
      - prod

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Deployment
        if: github.ref == 'refs/heads/dev'
        run: |
          git config user.name "cresoluser"
          git config user.email "cresoluser@gmail.com"
          git remote set-url origin https://x-access-token:${{ secrets.CICD }}@github.com/cresoluser/dev.git
      - name: Push to Dev Branch
        run: |
         git checkout -b dev
          git push -f origin dev
          # Setup for Dev Deployment
      - name: FTP Deploy to Dev
        if: github.ref == 'refs/heads/dev'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  
          server-dir: /dev
      - name: Setup Deployment
        if: github.ref == 'refs/heads/prod'
        run: |
          # Setup for Production Deployment
      - name: FTP Deploy to Production
        if: github.ref == 'refs/heads/prod'
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./  
          server-dir: /prod
